"""Regenerate `config/vertex_retention_set.txt` from the stimulus corpus.

    python scripts/build_vertex_retention_set.py --config config/tribe.yaml

Policy: retain the full `(T, V)` vertex array for the `primary` variant of
every unit in every condition; everything else is parcel-only.

This list is the only thing standing between a stimulus and permanent loss of
its vertex-level detail -- aggregation to parcels is one-way. The script
therefore never *shrinks* the retention set silently: an id already in the file
that the corpus no longer contains is reported and kept, because a prediction
may already have been computed and retained under it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.generation.stimulus_io import build_stimulus_index  # noqa: E402
from src.tribe.config import load_config  # noqa: E402

RETAINED_VARIANT = "primary"

HEADER = """\
# Stimulus ids whose full (T, V) vertex array is retained permanently (§4.5).
#
# GENERATED by scripts/build_vertex_retention_set.py -- edit that policy, not
# this list, unless you are deliberately retaining a one-off.
#
# Everything not listed here is aggregated to parcels and the vertex array is
# discarded. That discard is IRREVERSIBLE.
#
# Policy: the `{variant}` variant of every unit, in every condition.
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, help="path to config/tribe.yaml")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    config = load_config(args.config)
    index = build_stimulus_index(config.project_root)

    selected = sorted(
        stimulus_id
        for stimulus_id, entry in index.items()
        if str(entry["variant"]) == RETAINED_VARIANT
    )
    if not selected:
        raise SystemExit(
            f"no stimulus has variant {RETAINED_VARIANT!r}; refusing to write an empty "
            f"retention set, which would discard every vertex array"
        )

    existing = set(config.read_vertex_retention_set()) if config.vertex_retention_set.exists() else set()
    orphaned = sorted(existing - set(selected))
    if orphaned:
        print(
            f"keeping {len(orphaned)} id(s) already in the file but no longer in the corpus "
            f"(a retained prediction may exist for them): {orphaned}"
        )

    lines = [HEADER.format(variant=RETAINED_VARIANT), ""]
    lines += sorted(set(selected) | set(orphaned))
    config.vertex_retention_set.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {config.vertex_retention_set} with {len(set(selected) | set(orphaned))} id(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
