"""Generate `docs/metrics_reference.md` from the metric docstrings (gate 19).

    python scripts/build_metrics_reference.py

Decision gate 19 says no cortical metric may be interpreted until its direction
and meaning are documented. This script is that gate in executable form: it
reads the docstring of every registered metric, requires all four structured
fields, and fails if one is missing or if `Direction` is not one of the two
allowed values.

The reference is never hand-written. If it disagrees with the code, the code
wins and this script is what makes that true.
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.analysis import neural_metrics  # noqa: E402

REQUIRED_FIELDS = ("Formula", "Units", "Increase means", "Direction")
ALLOWED_DIRECTIONS = ("meaningful", "ambiguous")

_FIELD_RE = re.compile(
    r"^(?P<indent>\s*)(?P<field>Formula|Units|Increase means|Direction):\s*(?P<value>.*)$"
)

SECTIONS = (
    ("Per-parcel time-series metrics", neural_metrics.TIMESERIES_METRICS),
    ("Whole-cortex spatial metrics", neural_metrics.SPATIAL_METRICS),
    ("Cross-stimulus metrics", neural_metrics.CROSS_STIMULUS_METRICS),
)


class DocstringError(ValueError):
    """Raised when a metric docstring does not satisfy decision gate 19."""


def parse_docstring(name: str, doc: str | None) -> Tuple[str, Dict[str, str]]:
    """Split a metric docstring into its summary and its four gate-19 fields.

    Continuation lines are those indented deeper than the field label, so the
    free prose that follows a field block (``Requires ...``, ``Raises ...``) is
    not swallowed into it.
    """
    if not doc:
        raise DocstringError(f"{name}: has no docstring (decision gate 19)")

    lines = inspect.cleandoc(doc).splitlines()
    summary = lines[0].strip() if lines else ""

    fields: Dict[str, str] = {}
    current: str | None = None
    current_indent = 0
    for line in lines:
        match = _FIELD_RE.match(line)
        if match:
            current = match.group("field")
            current_indent = len(match.group("indent"))
            fields[current] = match.group("value").strip()
            continue
        if current is None:
            continue
        stripped = line.strip()
        indent = len(line) - len(line.lstrip())
        if stripped and indent > current_indent:
            fields[current] = f"{fields[current]} {stripped}".strip()
        else:
            current = None

    missing = [f for f in REQUIRED_FIELDS if not fields.get(f)]
    if missing:
        raise DocstringError(
            f"{name}: docstring is missing required field(s) {missing}. Decision gate 19 "
            f"requires every metric to state its Formula, Units, what an Increase means, and "
            f"whether its Direction is meaningful or ambiguous."
        )
    direction = fields["Direction"].split()[0].strip(" .,:-").lower()
    if direction not in ALLOWED_DIRECTIONS:
        raise DocstringError(
            f"{name}: Direction must start with one of {list(ALLOWED_DIRECTIONS)}; got "
            f"{fields['Direction']!r}"
        )
    fields["_direction_word"] = direction
    return summary, fields


def render() -> str:
    out: List[str] = [
        "# Metrics reference (§6.5, decision gate 19)",
        "",
        "Generated by `scripts/build_metrics_reference.py` from the docstrings in",
        "`src/analysis/neural_metrics.py`. **Do not edit by hand** -- rerun the script.",
        "",
        "Gate 19: no cortical metric is interpreted until its direction and meaning are",
        "documented. `Direction: meaningful` means a larger value has one interpretation;",
        "`ambiguous` means it does not, and the metric may only be read as a contrast",
        "between matched conditions.",
        "",
        "Every quantity below is a property of a *predicted* cortical response from an",
        "encoding model. None of them is a measurement of a brain, and none is a measure",
        "of learning.",
        "",
    ]

    counts = {"meaningful": 0, "ambiguous": 0}
    for heading, names in SECTIONS:
        out += [f"## {heading}", ""]
        for name in names:
            function = getattr(neural_metrics, name)
            summary, fields = parse_docstring(name, function.__doc__)
            counts[fields["_direction_word"]] += 1
            signature = str(inspect.signature(function))
            out += [
                f"### `{name}`",
                "",
                f"`{name}{signature}`",
                "",
                summary,
                "",
                f"- **Formula:** {fields['Formula']}",
                f"- **Units:** {fields['Units']}",
                f"- **An increase means:** {fields['Increase means']}",
                f"- **Direction:** {fields['Direction']}",
                "",
            ]

    out += [
        "## Summary",
        "",
        f"- metrics with a directionally meaningful increase: **{counts['meaningful']}**",
        f"- metrics whose direction is ambiguous: **{counts['ambiguous']}**",
        "",
        "Whole-cortex metrics are stored with "
        f"`parcel_id = {neural_metrics.WHOLE_CORTEX}` and computed over the "
        f"`{neural_metrics.SPATIAL_BASIS}` spatial summary.",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent.parent / "docs" / "metrics_reference.md"),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the docstrings and report drift without writing",
    )
    args = parser.parse_args()

    content = render()
    out_path = Path(args.out)

    if args.check:
        if not out_path.exists():
            print(f"{out_path} does not exist", file=sys.stderr)
            return 1
        if out_path.read_text(encoding="utf-8") != content:
            print(f"{out_path} is out of date; rerun without --check", file=sys.stderr)
            return 1
        print(f"{out_path} is up to date")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
